### PR TITLE
rgw/sfs: Add GC for done and aborted multiparts

### LINKED ISSUE #657: [BUG] GC: individual parts of completed multipart uploads are never deleted
**Describe the bug**

When a multipart upload completes, the parts are all stuck together and the completed file is copied to its final location, but the individual parts remain on disk. Per discussion on Slack, this should be handled by the garbage collector, but it's not happening. AFAICT the problem is that it just hasn't been implemented yet (see https://github.com/aquarist-labs/ceph/blob/49eea5c18d5f526e2c27637d42a232723e0041fc/src/rgw/driver/sfs/sfs_gc.cc#L37-L48).

**To Reproduce**

1. Do a multipart upload (e.g. `echo test | s3cmd put - s3://foo/test`)
2. `ls -R` the s3gw datastore and observe that there's two files present, one the multipart part from the (tiny) upload in step 1, the other the final file.
3. `dd if=/dev/urandom of=/dev/stdout bs=1M count=100 | s3cmd -c .s3cfg-test put - s3://foo/random` also works if you want to see lots of parts.
4. Note also that there's still entries in the `multiparts` and `multiparts_parts` tables in the database.

**Expected behavior**

Once a multipart upload is completed, the temporary parts should be removed.

### PR DESCRIPTION
**Pull request by 0xavi0**
This PR adds the code for dealing with aborted and done multiparts and their parts.

It also adds a minimal refactoring to the main GC method so it lists the GC steps in a more clear way.

Fixes: https://github.com/aquarist-labs/s3gw/issues/657

Signed-off-by: Xavi Garcia <xavi.garcia@suse.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

### CODE REVIEW

File: src/rgw/driver/sfs/sqlite/sqlite_multipart.cc [hunk 1]
```diff
@@ -512,4 +512,71 @@ SQLiteMultipart::remove_multiparts_by_bucket_id_transact(
...
+        inner_join<DBMultipart>(
+            on(is_equal(&DBMultipart::upload_id, &DBMultipartPart::upload_id))
+        ),
+        where(
+            is_equal(&DBMultipart::state, MultipartState::DONE) or
+            is_equal(&DBMultipart::state, MultipartState::ABORTED)
+        ),
+        order_by(&DBMultipartPart::id), limit(max_items)
+    );
+    ceph_assert(ids.size() == ret_parts.size());
```
Comment (irq0) [inline src/rgw/driver/sfs/sqlite/sqlite_multipart.cc:559]: How about using ranges::transform to extract get<2>(row) into a std array instead of doing another query?

File: src/rgw/driver/sfs/sqlite/sqlite_multipart.cc [hunk 2]
```diff
@@ -512,4 +512,71 @@ SQLiteMultipart::remove_multiparts_by_bucket_id_transact(
...
+    if (ret_parts.size() == 0) {
+      // nothing to be deleted. We can return now
+      // no need to commit the transaction as nothing was changed
+      return ret_parts;
+    }
+    // remove the parts selected
+    storage.remove_all<DBMultipartPart>(where(in(&DBMultipartPart::id, ids)));
+
+    // now check if the multipart holding the part is empty
```
Comment (irq0) [inline src/rgw/driver/sfs/sqlite/sqlite_multipart.cc]: If the MP is DONE or ABORTED new parts are unlikely. Only way I can think of is if something is in flight while doing the state change. With that unlikely how about making this common case fast style? 

Example: 
```
for upload in upload ids:
  try:
   DELETE FROM mulitparts where upload_id in $upload_ids
  except Constraint failed:
   log and move on. next GC run will find this thing again, since there are parts left
```
Another suggestion: build a std::set<upload_id> from get<0> of ret_parts?

**Review by irq0 — DISMISSED** [review]
Two suggestions, otherwise looks good to me

File: src/rgw/driver/sfs/sqlite/sqlite_multipart.cc (hunk 1 above)
Comment (0xavi0) [reply src/rgw/driver/sfs/sqlite/sqlite_multipart.cc:559]: I had to fix a couple of conflicts in the branch and added this suggestion.

File: src/rgw/driver/sfs/sqlite/sqlite_multipart.cc (hunk 2 above)
Comment (0xavi0) [reply src/rgw/driver/sfs/sqlite/sqlite_multipart.cc]: I did the exception thing with buckets in another PR, but I'm not sure I like it. Looks like forcing things a bit to me.
It's like... I'm doing something that might break a constraint and I know it but I'm catching the exception so nobody sees it. 

I still think we could possibly discuss if we could benefit from "on delete cascade" feature.... that way deletions are very simple, we would just delete parts and sqlite would deal itself with parents with no children.

That way all that "delete things" code would be simpler and cleaner.

Maybe something to talk about in a devs call...

Comment (irq0) [reply src/rgw/driver/sfs/sqlite/sqlite_multipart.cc]: > I did the exception thing with buckets in another PR, but I'm not sure I like it. Looks like forcing things a bit to me.
> It's like... I'm doing something that might break a constraint and I know it but I'm catching the exception so nobody sees it.

I think we have EAFP (Easier to ask for forgiveness than permission) vs. LBYL (Look before you leap) here :)

The python glossary explains the two approaches quite well: https://docs.python.org/3/glossary.html#term-EAFP
https://docs.python.org/3/glossary.html#term-LBYL

I'll add it to the devs meeting agenda.

Comment (irq0) [reply src/rgw/driver/sfs/sqlite/sqlite_multipart.cc]: > I still think we could possibly discuss if we could benefit from "on delete cascade" feature.... that way deletions are very simple, we would just delete parts and sqlite would deal itself with parents with no children.

If it fits cascading multipart deletes to MP parts children sounds very good. Does the select query at the start of the transaction protect us from a change in parts between select and delete cascade?

**Review by irq0 — APPROVED** [review]
