### PR TITLE
Make MP mark_complete a write transaction

### LINKED ISSUE #710: [BUG] concurrent multipart uploads occasionally raises unhandled exception
**Describe the bug**

Running concurrent multipart puts results in occasional failures, e.g.:

```
> s3cmd -c .s3cfg-test put - s3://foo/test-single-B-132
[...]
WARNING: Upload failed: /test-single-B-132?partNumber=1&uploadId=20230915T094808.800730568Z (500 (InternalError))
WARNING: Waiting 3 sec...
```

The s3gw log will show something like this:

```
2023-09-15T19:47:39.752+1000 7f4d4e9b16c0  0 req 0 0.003333303s s3:put_obj !!! BUG Unhandled exception while executing operation put_obj: database is locked
: database is locked. replying internal error
2023-09-15T19:47:39.752+1000 7f4d541bc6c0  1 ====== req done req=0x7f4ce20d76e0 op status=0 http_status=200 latency=0.003333303s ======
2023-09-15T19:47:39.752+1000 7f4d541bc6c0  1 beast: 0x7f4ce20d76e0: 127.0.0.1 - testid [15/Sep/2023:19:47:39.749 +1000] "POST /foo/test-single-B-34?uploads 
HTTP/1.1" 200 243 - - - latency=0.003333303s
2023-09-15T19:47:39.755+1000 7f4d4e9b16c0  0 req 0 0.006666606s s3:put_obj START BACKTRACE (exception St12system_error)
 ceph version s3gw-v0.20.0-rc2-34-g2cf997b980c (2cf997b980ca03ee54b87ec46241ebbdac036ed9) reef (dev)
 1: (rgw_process_authenticated(RGWHandler_REST*, RGWOp*&, RGWRequest*, req_state*, optional_yield, rgw::sal::Driver*, bool)+0x106d) [0x55856a0b9756]
 2: (process_request(RGWProcessEnv const&, RGWRequest*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RGWRestfulIO
*, optional_yield, rgw::dmclock::Scheduler*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::chrono::duration<unsigne
d long, std::ratio<1l, 1000000000l> >*, int*)+0x13ab) [0x55856a0bb0ba]
 3: bin/radosgw(+0x208ba0e) [0x55856a016a0e]
 4: bin/radosgw(+0x208c546) [0x55856a017546]
 5: bin/radosgw(+0x208c703) [0x55856a017703]
 6: bin/radosgw(+0x208c874) [0x55856a017874]
 7: bin/radosgw(+0x208c943) [0x55856a017943]
 8: make_fcontext()

END BACKTRACE
```

`s3cmd` retries the put, so everything ultimately works, but I don't like the look of that ` !!! BUG Unhandled exception` thing. Three exclamation marks must be bad, right? ;-)

**To Reproduce**:

1. Run the radosgw binary (I'm using `bin/radosgw -i bar -d --no-mon-config --debug-rgw 1   --rgw-backend-store sfs   --rgw-data $(pwd)/dev/rgw.bar --run-dir $(pwd)/dev/rgw.bar --rgw-sfs-data-path $(pwd)/dev/rgw.bar --rgw-gc-processor-period 3600 --rgw-frontends 'beast port=7480,status port=9090' > $(pwd)/dev/rgw.bar/s3gw.log` in my source checkout)
2. Run several instances of something like `echo test | s3cmd put - s3://foo/test` in a loop (e.g.: `for i in $(seq 1 100) ; do echo test | s3cmd put - s3://foo/test-single-A-$i  ; done` in a few different terminal windows)
3. Watch the terminal windows and s3gw.log and wait for errors.

**Expected behavior**

No errors.

**Additional context**

Note: this is running from the head of our s3gw branch of ceph on 2023-09-15, i.e. https://github.com/aquarist-labs/ceph/commit/2cf997b980ca03ee54b87ec46241ebbdac036ed9

### PR DESCRIPTION
**Pull request by irq0**
Make SQLiteMultipart::mark_complete a write transaction so that the
default retry timeout handler kicks in.

Fixes: https://github.com/aquarist-labs/s3gw/issues/710#issuecomment-1757011216

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

### CODE REVIEW

File: src/rgw/driver/sfs/sqlite/sqlite_multipart.cc [hunk 1]
```diff
@@ -344,59 +344,33 @@ bool SQLiteMultipart::abort(const std::string& upload_id) const {
...
+      const auto state = storage.select(
+          columns(&DBMultipart::state),
+          where(is_equal(&DBMultipart::upload_id, upload_id))
+      );
+      if (state.size() == 0) {
+        return false;
+      }
+      *duplicate = (std::get<0>(state[0]) >= MultipartState::COMPLETE);
+    } else {
+      *duplicate = false;
```
Comment (jecluis) [inline src/rgw/driver/sfs/sqlite/sqlite_multipart.cc:372]: To clarify, this only makes the operation **potentially** write-only, right? If the conditions are met, this will still be a read-write transaction. Or am I misunderstanding the point?

Comment (irq0) [reply src/rgw/driver/sfs/sqlite/sqlite_multipart.cc:372]: It is a write transaction, because it starts with an update. Write transactions may also do reads. Read-then-write transactions require an upgrade to a write transaction. Starting the write transaction directly is subject to the busy timeout handler. The read-then-write in many of our cases not. They may trigger the deadlock prevention logic if multiple concurrent connections already have the read lock. 

This gives us two options to get transaction retries: the busy transaction retry utility or starting with writes to use the busy timeout handler. 

Since the update is the important bit here and not dependent on a previous select, making it a write transaction makes most sense I think.

Related docs:
https://www.sqlite.org/lang_transaction.html#:~:text=2.1.%20Read%20transactions%20versus%20write%20transactions

Comment (jecluis) [reply src/rgw/driver/sfs/sqlite/sqlite_multipart.cc:372]: Yep, makes sense. Thanks! :)

**Review by jecluis — APPROVED** [review]
