### PR TITLE
rgw/sfs: Implement new versioning design

### LINKED ISSUE #378: Transact object create + object version create
### What needs to be done

Add transactions for combined obj create + version create operations.
https://github.com/aquarist-labs/ceph/pull/124 adds TODO comments to mark (some) of the spots.

Wait for https://github.com/aquarist-labs/ceph/pull/124.

### LINKED ISSUE #472: Check and improve versioning s3tests
Right now we are running only 7 out of 21 s3 tests for versioning, because the rest are either failing or not checked for a long time.

It would be good to have a better s3 tests versioning coverage, which would mean that we are following the S3 standard for that particular area. 

This is the list of tests not being executed

- test_bucket_list_return_data_versioning
- test_object_copy_versioning_multipart_upload
- test_versioning_obj_create_read_remove
- test_versioning_obj_create_read_remove_head
- test_versioning_obj_plain_null_version_overwrite
- test_versioning_obj_suspend_versions
- test_versioning_obj_create_versions_remove_all
- test_versioning_obj_create_versions_remove_special_names
- test_versioning_obj_create_overwrite_multipart
- test_versioning_obj_list_marker
- test_versioning_copy_obj_version
- test_versioning_multi_object_delete
- test_versioning_multi_object_delete_with_maker

### LINKED ISSUE #519: Bucket Recreate Operation
A create bucket operation on an existing bucket is a recreate operation not a failure.

We currently treat it as such, replying EEXIST

## Tests

test_bucket_recreate_not_overriding	

## Additional context
https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateBucket.html

### LINKED ISSUE #524: List after multi object delete returns deleted objects
S3 tests: test_multi_objectv2_delete, test_multi_object_delete	

Test result:
```
        response = client.delete_objects(Bucket=bucket_name, Delete=objs_dict)
        assert len(response['Deleted']) == 3
        assert 'Errors' not in response
        response = client.list_objects(Bucket=bucket_name)
>       assert 'Contents' not in response
E       assert 'Contents' not in {'Contents': [{'ETag': '"21f402f25b1a0fd722b83169e10509f8"', 'Key': 'key0', 'LastModified': datetime.datetime(2023, 5, 16, 11, 13, 59, 9000, tzinfo=tzutc()), 'Owner': {'DisplayName': 'youruseridhere', 'ID': '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'}, ...}, {'ETag': '"c2add694bf942dc77b376592d9c862cd"', 'Key': 'key1', 'LastModified': datetime.datetime(2023, 5, 16, 11, 13, 59, 28000, tzinfo=tzutc()), 'Owner': {'DisplayName': 'youruseridhere', 'ID': '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'}, ...}, {'ETag': '"78f825aaa0103319aaa1a30bf4fe3ada"', 'Key': 'key2', 'LastModified': datetime.datetime(2023, 5, 16, 11, 13, 59, 48000, tzinfo=tzutc()), 'Owner': {'DisplayName': 'youruseridhere', 'ID': '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'}, ...}], 'EncodingType': 'url', 'IsTruncated': False, 'Marker': '', ...}
```

### LINKED ISSUE #526: head_object/get_object/ more: Missing VersionId in response
Many responses don't have the VersionID / x-amz-version-id set.

For head_object requests:

head object requests..
are RGWGetObj RGW operations with get_data == false..
create a ReadOp, call prepare, never call iterate()..
retrieve attrs by calling get_attrs on the SAL object
retrieve the version_id from object get_instance()

relevant op code:
```
  op_ret = read_op->prepare(s->yield, this);
  if (op_ret < 0)
    goto done_err;
  version_id = s->object->get_instance();
  s->obj_size = s->object->get_obj_size();
  attrs = s->object->get_attrs();
```

Theory: we don't set the instance in the object's cached state (RGWObjState)

S3 Tests failing because of this:

test_object_lock_delete_object_with_retention_and_marker	fail
test_object_lock_get_obj_metadata	fail
test_object_lock_uploading_obj	fail
test_versioned_object_acl_no_version_specified	fail
test_versioning_multi_object_delete_with_marker	fail
test_versioning_obj_plain_null_version_overwrite	fail

### LINKED ISSUE #547: [BUG] rgw/sfs: The `LastModified` field of an deleted object is not updated
If an object is deleted, the `LastModified` field of the delete marker is not set to the deletion date.

```
{
    "Versions": [
        {
            "ETag": "\"d64d9775216d967b6d8d4726d54386ed\"",
            "Size": 514,
            "StorageClass": "STANDARD",
            "Key": "file2.txt",
            "VersionId": "cGxFS0lMiE7rIT2BDRay9MUZiDIhjoX",
            "IsLatest": false,
            "LastModified": "2023-05-25T08:26:33.622Z",
            "Owner": {
                "DisplayName": "M. Tester",
                "ID": "testid"
            }
        },
        {
            "ETag": "\"75ec5355d8c2c299d9ff530edbb248fc\"",
            "Size": 410,
            "StorageClass": "STANDARD",
            "Key": "file2.txt",
            "VersionId": "jKnK94CzV8BGb3XodXNr0OWcbgKh9QQ",
            "IsLatest": false,
            "LastModified": "2023-05-25T08:26:37.549Z", <-------- Same date as the deletion marker
            "Owner": {
                "DisplayName": "M. Tester",
                "ID": "testid"
            }
        }
    ],
    "DeleteMarkers": [
        {
            "Owner": {
                "DisplayName": "M. Tester",
                "ID": "testid"
            },
            "Key": "file2.txt",
            "VersionId": "XuH-ucgmis.jaVOujvVmrIsYOPgxunX",
            "IsLatest": true,
            "LastModified": "2023-05-25T08:26:37.549Z"  <------ The same date as the version that has been deleted.
        }
    ]
}
```

Bildschirmfoto vom 2023-05-25 11-24-39

### PR DESCRIPTION
**Pull request by 0xavi0**
Implements new versioning design following [this ADR](https://github.com/aquarist-labs/s3gw/blob/main/docs/decisions/0010-sfs-versioning.md) 

* Includes `rgw::sal::Attrs` type binding in `sqliteorm` code, so VersionedObject code for conversions is no longer needed.

    Any value that was a `BLOB` before and that it's not optional should be good to be bound.
    Just declare the type in the database struct and add this:
    ```c++
     #include "rgw/driver/sfs/sqlite/bindings/blob.h"
     ```
     That file uses the previous code to convert `ceph` types using `bufferlist` ("rgw/driver/sfs/sqlite/conversion_utils.h")

     Extra code for dealing with optional `BLOB` will be proposed in a future PR and we'll be able to delete all the conversion 
     layers where no strictly needed.

* Adds transactions for the actions that require more than 1 database access.

* Simplifies the way a new version is created and moves its logic to a sqlite transaction to avoid race conditions when creating N objects with the same name at once from several threads.

* Also changed the name of the objects and versioned_objects table names to `DBObject` and `DBVersionedObject`

The following `s3 tests` now pass:
```
test_bucket_list_return_data_versioning
test_object_copy_versioning_multipart_upload
test_versioning_bucket_create_suspend
test_versioning_obj_create_read_remove
test_versioning_obj_create_read_remove_head
test_versioning_obj_create_versions_remove_all
test_versioning_obj_create_versions_remove_special_names
test_versioning_obj_create_overwrite_multipart
test_versioning_obj_list_marker
test_versioning_copy_obj_version
test_versioning_multi_object_delete
test_versioning_multi_object_delete_with_marker
test_versioning_multi_object_delete_with_marker_create
test_lifecycle_expiration_versioning_enabled
test_versioning_bucket_atomic_upload_return_version_id
test_versioning_bucket_multipart_upload_return_version_id
test_object_lock_suspend_versioning
test_object_copy_versioned_bucket
test_object_copy_versioned_url_encoding
test_multipart_copy_versioned
test_versioned_object_acl
test_versioned_object_acl_no_version_specified
test_versioned_concurrent_object_create_concurrent_remove
test_versioned_concurrent_object_create_and_remove
test_multi_object_delete
test_multi_objectv2_delete
test_bucket_recreate_not_overriding
```

Fixes: https://github.com/aquarist-labs/s3gw/issues/378
Fixes: https://github.com/aquarist-labs/s3gw/issues/472
Fixes: https://github.com/aquarist-labs/s3gw/issues/547
Fixes: https://github.com/aquarist-labs/s3gw/issues/526
Fixes: https://github.com/aquarist-labs/s3gw/issues/524
Fixes: https://github.com/aquarist-labs/s3gw/issues/519

Signed-off-by: Xavi Garcia <xavi.garcia@suse.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

### CODE REVIEW

File: src/rgw/driver/dbstore/common/dbstore.h
Comment (jecluis) [inline src/rgw/driver/dbstore/common/dbstore.h:1]: huh... why are we changing dbstore code?

File: src/rgw/driver/sfs/object.cc [hunk 1]
```diff
@@ -162,12 +164,16 @@ int SFSObject::SFSDeleteOp::delete_obj(
   }
 
   auto version_id = source->get_instance();
+  std::string delete_marker_version_id;
   if (source->objref) {
-    bucketref->delete_object(source->objref, source->get_key());
-  } else if (source->bucket->versioning_enabled()) {
+    bucketref->delete_object(
+        source->objref, source->get_key(), source->bucket->versioning_enabled(),
+        delete_marker_version_id
```
Comment (jecluis) [inline src/rgw/driver/sfs/object.cc:171]: isn't `delete_marker_version_id` empty?

File: src/rgw/driver/sfs/object.cc [hunk 2]
```diff
@@ -162,12 +164,16 @@ int SFSObject::SFSDeleteOp::delete_obj(
...
+    );
+  } else if (source->bucket->versioning_enabled() && source->get_instance().empty()) {
     // create delete marker
     // even the object does not exist AWS creates a delete marker for it
-    // if versioning is enabled
+    // if versioning is enabled and an specific version was not specified
```
Comment (jecluis) [inline src/rgw/driver/sfs/object.cc]: nit: s/an/a/

File: src/rgw/driver/sfs/sqlite/versioned_object/versioned_object_definitions.h [hunk 3]
```diff
@@ -58,4 +41,77 @@ struct DBOPVersionedObjectInfo {
...
+) {
+  return std::get<10>(item);
+}
+
+inline decltype(DBVersionedObject::object_state) get_object_state(
+    const DBObjectsListItem& item
+) {
+  return std::get<11>(item);
+}
+
```
Comment (jecluis) [inline src/rgw/driver/sfs/sqlite/versioned_object/versioned_object_definitions.h:116]: okay, this is awesome xD

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc [hunk 4]
```diff
@@ -13,110 +13,380 @@
...
+        // if not value is found could be, for example, if lifecycle deleted all
+        // non current versions before.
+        auto last_version_id = std::get<0>(max_commit_time_ids[0]);
+        auto last_version =
+            storage.get_pointer<DBVersionedObject>(last_version_id);
+        if (last_version) {
+          ret_value = *last_version;
+        }
+      }
+      transaction.commit();
```
Comment (jecluis) [inline src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc:269]: I think we either need this `commit()` to happen outside this `if` block, or have an `abort()` at the end. Because it seems to me that if `version == nullptr`, then this transaction would never be finished and `storage` could potentially be left in a state where a transaction is on-going.

Alternatively, use a lambda function for the transaction, instead of a transaction guard.

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc [hunk 5]
```diff
@@ -13,110 +13,380 @@
...
+          is_equal(&DBObject::name, object_name) and
+          is_equal(&DBVersionedObject::version_id, version_id)
+      )
   );
-  std::optional<DBOPVersionedObjectInfo> ret_value;
-  if (last_version_id) {
-    auto last_version =
-        storage.get_pointer<DBVersionedObject>(*last_version_id);
+  // TODO return an error if this returns more than 1 version?
+  // Only 1 object with no deleted versions should be present
```
Comment (jecluis) [inline src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc:348]: maybe assert instead? If that happens, it feels like the database is broken.

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc [hunk 6]
```diff
@@ -13,110 +13,380 @@
...
+      ),
+      where(
+          is_equal(&DBObject::bucket_id, bucket_id) and
+          is_equal(&DBObject::name, object_name) and
+          is_not_equal(&DBVersionedObject::object_state, ObjectState::DELETED)
+      ),
+      group_by(&DBVersionedObject::id), order_by(&DBVersionedObject::id).desc()
+  );
+  auto found_value = max_commit_time_ids.size() &&
+                     std::get<1>(max_commit_time_ids[0]) != nullptr;
```
Comment (jecluis) [inline src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc:381]: Can the commit time ever be a `nullptr`? From the `DBVersionedObject::commit_time` definition, it seems to be just a `ceph::real_time` object, not a pointer, not even an `std::optional`. Also, `std::get()` seems to always return a reference, so it wouldn't return a `nullptr` either.

At most, it seems we would be checking for an "empty" time, which I think would be the beginning of the unix time epoch.

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc [hunk 7]
```diff
@@ -13,110 +13,380 @@
...
+            ) and
+            is_equal(&DBObject::bucket_id, bucket_id) and
+            is_equal(&DBObject::name, object_name)
+        ),
+        group_by(&DBObject::uuid)
+    );
+    // should return none or 1
+    // TODO throw error if it returns more than 1 when error handling is
+    // defined? (only 1 object with the same name and not deleted should be
+    // found)
```
Comment (jecluis) [inline src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc]: if this is a sanity constraint, I think the right thing is to assert.

File: src/rgw/driver/sfs/types.cc [hunk 8]
```diff
@@ -469,14 +417,50 @@ void Bucket::_undelete_object(
...
+  auto last_version =
+      db_versioned_objs.get_last_versioned_object(objref->path.get_uuid());
+  if (last_version.has_value() &&
+      last_version->object_state == ObjectState::COMMITTED) {
+    last_version->version_type = VersionType::DELETE_MARKER;
+    last_version->delete_time = now;
+    last_version->mtime = now;
+    last_version->version_id = generate_new_version_id(store->ceph_context());
+    objref->instance = last_version->version_id;
+    db_versioned_objs.insert_versioned_object(*last_version);
```
Comment (jecluis) [inline src/rgw/driver/sfs/types.cc]: shouldn't this be part of a single transaction? we're inserting something based on a value that we are reading, without ensuring that nothing else happens in between.

**Review by jecluis — COMMENTED** [review]
generally looks good, but a few comments I'd like answers to before approving or requesting changes :)

File: src/rgw/driver/sfs/object.cc (hunk 1 above)
Comment (0xavi0) [reply src/rgw/driver/sfs/object.cc:171]: no, that's a return value.
```c++
  /// S3 delete object operation: delete version or create tombstone.
  /// If a delete marker was added, it returns the new version id generated for
  /// it
  void delete_object(
      ObjectRef objref, const rgw_obj_key& key, bool versioned_bucket,
      std::string& delete_marker_version_id
  );
```
Delete object might be creating a delete marker. In that case we need to generate a `version_id` for it.
It returns it so we can add it to the response.

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc (hunk 4 above)
Comment (0xavi0) [reply src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc:269]: If my understanding is correct (I'll double check) transaction guard calls `rollback` when it gets out of scope if `commit()` or `rollback` themselves were not called before.
So, in this case... if the version is `nullptr` it should simply `rollback`.

Code is this:
```c++
namespace sqlite_orm {

    namespace internal {

        /**
         *  Class used as a guard for a transaction. Calls `ROLLBACK` in destructor.
         *  Has explicit `commit()` and `rollback()` functions. After explicit function is fired
         *  guard won't do anything in d-tor. Also you can set `commit_on_destroy` to true to
         *  make it call `COMMIT` on destroy.
         * 
         *  Note: The guard's destructor is explicitly marked as potentially throwing,
         *  so exceptions that occur during commit or rollback are propagated to the caller.
         */
        struct transaction_guard_t {
            /**
             *  This is a public lever to tell a guard what it must do in its destructor
             *  if `gotta_fire` is true
             */
            bool commit_on_destroy = false;

            transaction_guard_t(connection_ref connection_,
                                std::function<void()> commit_func_,
                                std::function<void()> rollback_func_) :
                connection(std::move(connection_)),
                commit_func(std::move(commit_func_)), rollback_func(std::move(rollback_func_)) {}

            transaction_guard_t(transaction_guard_t&& other) :
                commit_on_destroy(other.commit_on_destroy), connection(std::move(other.connection)),
                commit_func(std::move(other.commit_func)), rollback_func(std::move(other.rollback_func)),
                gotta_fire(other.gotta_fire) {
                other.gotta_fire = false;
            }

            ~transaction_guard_t() noexcept(false) {
                if(this->gotta_fire) {
                    if(this->commit_on_destroy) {
                        this->commit_func();
                    } else {
                        this->rollback_func();
                    }
                }
            }

            transaction_guard_t& operator=(transaction_guard_t&&) = delete;

            /**
             *  Call `COMMIT` explicitly. After this call
             *  guard will not call `COMMIT` or `ROLLBACK`
             *  in its destructor.
             */
            void commit() {
                this->gotta_fire = false;
                this->commit_func();
            }

            /**
             *  Call `ROLLBACK` explicitly. After this call
             *  guard will not call `COMMIT` or `ROLLBACK`
             *  in its destructor.
             */
            void rollback() {
                this->gotta_fire = false;
                this->rollback_func();
            }

          protected:
            connection_ref connection;
            std::function<void()> commit_func;
            std::function<void()> rollback_func;
            bool gotta_fire = true;
        };
    }
}
```

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc (hunk 5 above)
Comment (0xavi0) [reply src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc:348]: I can do that, yeah... That's some of the things we'd need to discuss when talking about error handling.
I'll `assert` for now... because yes, only 1 "alive" object should be found at a given moment.

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc (hunk 6 above)
Comment (0xavi0) [reply src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc:381]: oh, that's because the type of 
```c++ 
sqliteorm::max(&DBVersionedObject::commit_time)
```
is returned as:
```c++
std::unique_ptr<ceph::real_time>
```
In the case that there are no results... that's the way `sqliteorm` returns `NULL` values for aggregators.
So that code is checking that the max commit time is, indeed, valid.

That's why I added the extra helpers to work with tuple results, because some of the return types from `sqliteorm` are 
 sometimes not obvious.

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc (hunk 7 above)
Comment (0xavi0) [reply src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc]: Yup, I'll do that meanwhile we decide that to do in the error handling call

File: src/rgw/driver/sfs/types.cc (hunk 8 above)
Comment (0xavi0) [reply src/rgw/driver/sfs/types.cc]: oh, you're right... I'll change it

File: src/rgw/driver/sfs/object.cc (hunk 2 above)
Comment (0xavi0) [reply src/rgw/driver/sfs/object.cc]: Will fix

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc (hunk 4 above)
Comment (jecluis) [reply src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc:269]: gotcha, thanks!

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc (hunk 6 above)
Comment (jecluis) [reply src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc:381]: oh, I missed the `max()` in the select. Alright, thanks!

File: src/rgw/driver/sfs/object.cc (hunk 1 above)
Comment (jecluis) [reply src/rgw/driver/sfs/object.cc:171]: okay, thanks :)

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc [hunk 9]
```diff
@@ -13,110 +13,429 @@
...
+          last_version->version_type == VersionType::REGULAR) {
+        auto now = ceph::real_clock::now();
+        last_version->version_type = VersionType::DELETE_MARKER;
+        last_version->delete_time = now;
+        last_version->mtime = now;
+        last_version->version_id = delete_marker_id;
+        ret_id = storage.insert(*last_version);
+        added = true;
+        /// only commit if the delete maker was indeed inserted.
+        /// the rest of calls in this transaction are read operations
```
Comment (jecluis) [inline src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc]: I would drop the docstring from these, and make them regular comments.

File: src/rgw/driver/sfs/types.cc [hunk 10]
```diff
@@ -469,14 +417,61 @@ void Bucket::_undelete_object(
...
+  //   last_version->version_type = VersionType::DELETE_MARKER;
+  //   last_version->delete_time = now;
+  //   last_version->mtime = now;
+  //   last_version->version_id = generate_new_version_id(store->ceph_context());
+  //   objref->instance = last_version->version_id;
+  //   db_versioned_objs.insert_versioned_object(*last_version);
+  //   objref->deleted = true;
+  //   delete_marker_id = last_version->version_id;
+  // }
+  // delete marker was not added
```
Comment (jecluis) [inline src/rgw/driver/sfs/types.cc]: drop dead code?

**Review by jecluis — CHANGES_REQUESTED** [review]
cleanup related, otherwise looks good.

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc [hunk 11]
```diff
@@ -13,110 +13,429 @@
...
+    const std::string& bucket_id, const std::string& object_name,
+    const std::string& version_id
+) const {
+  if (version_id.empty()) {
+    return _get_versioned_object(bucket_id, object_name);
+  }
+  return _get_versioned_object(bucket_id, object_name, version_id);
+}
+
+DBObjectsListItems SQLiteVersionedObjects::list_last_versioned_objects(
```
Comment (irq0) [inline src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc:71]: Suggest to include the state the objects are in. The name does not imply that deleted objects are filtered out.

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc (hunk 9 above)
Comment (0xavi0) [reply src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc]: yup, fixed

File: src/rgw/driver/sfs/types.cc (hunk 10 above)
Comment (0xavi0) [reply src/rgw/driver/sfs/types.cc]: Dropped

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc [hunk 12]
```diff
@@ -13,110 +13,429 @@
...
+    }
+  } catch (const std::system_error& e) {
+    // throw exception (will be caught later in the sfs logic)
+    // TODO revisit this when error handling is defined
+    throw(e);
+  }
+  return ret_id;
+}
+
+std::optional<DBVersionedObject> SQLiteVersionedObjects::_get_versioned_object(
```
Comment (irq0) [inline src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc]: Method name does not imply that it only returns versions not in state deleted

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc [hunk 13]
```diff
@@ -13,110 +13,429 @@
...
+  if (ids.size() > 0) {
+    auto version = storage.get_pointer<DBVersionedObject>(ids[0]);
+    if (version != nullptr) {
+      ret_value = *version;
+    }
+  }
+  return ret_value;
+}
+
+std::optional<DBVersionedObject> SQLiteVersionedObjects::_get_versioned_object(
```
Comment (irq0) [inline src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc]: Same as overloaded one. Would be good to tell callers that this only returns non deleted versions

File: src/rgw/driver/sfs/bucket.cc [hunk 14]
```diff
@@ -238,12 +256,10 @@ bool SFSBucket::is_owner(User* user) {
 int SFSBucket::check_empty(const DoutPrefixProvider* dpp, optional_yield y) {
```
Comment (irq0) [inline src/rgw/driver/sfs/bucket.cc:256]: (Goold candidate to turn into an sql query in a future PR. )

Q: What is empty?
there is no committed version?
there is no committed or open (== in flight) version?
🤔 is a bucket empty if there are multpart uploads going on?

**Review by irq0 — COMMENTED** [review]
looks good!

I like how the code now leverages more of sqlite_orm.

General comments:

Some of the sql utility methods would benefit from names that imply if deleted is included or now.

The '\_' prefix. I've seen it in the python word for private methods, but not much in c++. What does it mean here? Just private method? Utility method? Method doing actual work (like the do_ prefix in many parts of the ceph codebase)

**Review by jecluis — DISMISSED** [review]

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc (hunk 11 above)
Comment (0xavi0) [reply src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc:71]: okay, sounds good to me. I've renamed it to `get_non_deleted_versioned_object`

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc (hunk 12 above)
Comment (0xavi0) [reply src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc]: Renamed as well... 
Deleted the `_` prefix and now those 2 private methods are more self-explanatory.
* `get_non_deleted_versioned_object_specific_version`
* `get_non_deleted_versioned_object_last_version`

(Previous names with `_` was just to use the same name as the public API method name but being private. I guess my brain used my previous company convention about private methods ¯\_(ツ)_/¯)

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc (hunk 13 above)
Comment (0xavi0) [reply src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc]: same as above

File: src/rgw/driver/sfs/bucket.cc (hunk 14 above)
Comment (0xavi0) [reply src/rgw/driver/sfs/bucket.cc:256]: Yup, I wonder if there are any `s3 tests` for this.

Comment (irq0) [reply src/rgw/driver/sfs/bucket.cc:256]: Surprising to me check_empty is only called from RGWDeleteBucket::execute before doing the remove_bucket call. Surprising because I would have expected that to be part of remove_bucket

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc (hunk 12 above)
Comment (irq0) [reply src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc]: 👍

File: src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc (hunk 13 above)
Comment (irq0) [reply src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc]: 👍

**Review by jecluis — DISMISSED** [review]

**Comment by jecluis** [comment]
@irq0 are you satisfied with the changes? Anything else comes to mind? I'd love to merge this soon-ish :)

File: src/rgw/driver/sfs/bucket.cc (hunk 14 above)
Comment (jecluis) [reply src/rgw/driver/sfs/bucket.cc:256]: The answer here needs to be, I think, that the multipart uploads are simply aborted if the bucket is removed. The multipart upload is a promise of eventually creating something in that bucket, and as such I don't think it's reasonable to hold the bucket to exist just because someone forgot to complete or abort a multipart upload.

Comment (irq0) [reply src/rgw/driver/sfs/bucket.cc:256]: Good to know, thanks!

**Review by irq0 — DISMISSED** [review]

**Comment by 0xavi0** [comment]
I'll merge as soon as CI passes

**Review by jecluis — APPROVED** [review]
