### PR TITLE
rgw/sfs: Don't return version id for unversioned buckets

### LINKED ISSUE #675: Getting / deleting tags with public access ACL fails
test_put_tags_acl_public fails with 
E           botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObjectTagging operation: Unknown

test_delete_tags_obj_public also failes with an access denied when deleting.

---
test_put_tags_acl_public

The test tries to do get_object_tagging on an object that grants public access. 

In the logs get_obj_tags fails with EACCESS. Previously the acl operation is reported successful.

```
2023-08-24T13:17:37.834+0000 7f30de37e6c0  2 req 0 0.000000000s s3:get_obj_tags normalizing buckets and tenants
2023-08-24T13:17:37.834+0000 7f30de37e6c0 10 req 0 0.000000000s s->object=testputtagsacl s->bucket=sfstest-wxqulxwlfm2ikd6g0byc4-1
2023-08-24T13:17:37.834+0000 7f30de37e6c0  2 req 0 0.000000000s s3:get_obj_tags init permissions
2023-08-24T13:17:37.834+0000 7f30de37e6c0 10 req 0 0.000000000s s3:get_obj_tags get_bucket: bucket: sfstest-wxqulxwlfm2ikd6g0byc4-1
2023-08-24T13:17:37.834+0000 7f30de37e6c0  2 req 0 0.000000000s s3:get_obj_tags recalculating target
2023-08-24T13:17:37.834+0000 7f30de37e6c0  2 req 0 0.000000000s s3:get_obj_tags reading permissions
2023-08-24T13:17:37.837+0000 7f30de37e6c0  2 req 0 0.003333419s s3:get_obj_tags init op
2023-08-24T13:17:37.837+0000 7f30de37e6c0 10 get_quota: TODO
2023-08-24T13:17:37.837+0000 7f30de37e6c0  2 req 0 0.003333419s s3:get_obj_tags verifying op mask
2023-08-24T13:17:37.837+0000 7f30de37e6c0  2 req 0 0.003333419s s3:get_obj_tags verifying op permissions
2023-08-24T13:17:37.837+0000 7f30de37e6c0  5 req 0 0.003333419s s3:get_obj_tags Searching permissions for identity=rgw::auth::SysReqApplier -> rgw::auth::LocalApplier(acct_user=56789abcdef0123456789abcdef0123456789abcdef0123456789abcdef01234, acct_name=john.doe, subuser=, perm_mask=15, is_admin=0) mask=49
2023-08-24T13:17:37.837+0000 7f30de37e6c0  5 req 0 0.003333419s s3:get_obj_tags Searching permissions for uid=56789abcdef0123456789abcdef0123456789abcdef0123456789abcdef01234
2023-08-24T13:17:37.837+0000 7f30de37e6c0  5 req 0 0.003333419s s3:get_obj_tags Permissions for user not found
2023-08-24T13:17:37.837+0000 7f30de37e6c0  5 req 0 0.003333419s s3:get_obj_tags Searching permissions for group=1 mask=49
2023-08-24T13:17:37.837+0000 7f30de37e6c0  5 req 0 0.003333419s s3:get_obj_tags Permissions for group not found
2023-08-24T13:17:37.837+0000 7f30de37e6c0  5 req 0 0.003333419s s3:get_obj_tags Searching permissions for group=2 mask=49
2023-08-24T13:17:37.837+0000 7f30de37e6c0  5 req 0 0.003333419s s3:get_obj_tags Permissions for group not found
2023-08-24T13:17:37.837+0000 7f30de37e6c0  5 req 0 0.003333419s s3:get_obj_tags -- Getting permissions done for identity=rgw::auth::SysReqApplier -> rgw::auth::LocalApplier(acct_user=56789abcdef0123456789abcdef0123456789abcdef0123456789abcdef01234, acct_name=john.doe, subuser=, perm_mask=15, is_admin=0), owner=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef, perm=0
2023-08-24T13:17:37.837+0000 7f30de37e6c0 10 req 0 0.003333419s s3:get_obj_tags  identity=rgw::auth::SysReqApplier -> rgw::auth::LocalApplier(acct_user=56789abcdef0123456789abcdef0123456789abcdef0123456789abcdef01234, acct_name=john.doe, subuser=, perm_mask=15, is_admin=0) requested perm (type)=1, policy perm=0, user_perm_mask=15, acl perm=0
2023-08-24T13:17:37.837+0000 7f30de37e6c0  5 req 0 0.003333419s s3:get_obj_tags Searching permissions for identity=rgw::auth::SysReqApplier -> rgw::auth::LocalApplier(acct_user=56789abcdef0123456789abcdef0123456789abcdef0123456789abcdef01234, acct_name=john.doe, subuser=, perm_mask=15, is_admin=0) mask=48
2023-08-24T13:17:37.837+0000 7f30de37e6c0  5 req 0 0.003333419s s3:get_obj_tags Searching permissions for uid=56789abcdef0123456789abcdef0123456789abcdef0123456789abcdef01234
2023-08-24T13:17:37.837+0000 7f30de37e6c0  5 req 0 0.003333419s s3:get_obj_tags Permissions for user not found
2023-08-24T13:17:37.837+0000 7f30de37e6c0  5 req 0 0.003333419s s3:get_obj_tags Searching permissions for group=1 mask=48
2023-08-24T13:17:37.837+0000 7f30de37e6c0  5 req 0 0.003333419s s3:get_obj_tags Permissions for group not found
2023-08-24T13:17:37.837+0000 7f30de37e6c0  5 req 0 0.003333419s s3:get_obj_tags Searching permissions for group=2 mask=48
2023-08-24T13:17:37.837+0000 7f30de37e6c0  5 req 0 0.003333419s s3:get_obj_tags Permissions for group not found
2023-08-24T13:17:37.837+0000 7f30de37e6c0  5 req 0 0.003333419s s3:get_obj_tags -- Getting permissions done for identity=rgw::auth::SysReqApplier -> rgw::auth::LocalApplier(acct_user=56789abcdef0123456789abcdef0123456789abcdef0123456789abcdef01234, acct_name=john.doe, subuser=, perm_mask=15, is_admin=0), owner=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef, perm=0
2023-08-24T13:17:37.837+0000 7f30de37e6c0 10 req 0 0.003333419s s3:get_obj_tags  identity=rgw::auth::SysReqApplier -> rgw::auth::LocalApplier(acct_user=56789abcdef0123456789abcdef0123456789abcdef0123456789abcdef01234, acct_name=john.doe, subuser=, perm_mask=15, is_admin=0) requested perm (type)=16, policy perm=0, user_perm_mask=16, acl perm=0
2023-08-24T13:17:37.837+0000 7f30de37e6c0  1 req 0 0.003333419s op->ERRORHANDLER: err_no=-13 new_err_no=-13
2023-08-24T13:17:37.837+0000 7f30de37e6c0  2 req 0 0.003333419s s3:get_obj_tags op status=0
2023-08-24T13:17:37.837+0000 7f30de37e6c0  2 req 0 0.003333419s s3:get_obj_tags http status=403
```

### LINKED ISSUE #695: Get Object with LC rule doesn't set always set x-amz-expiration header
Two s3 tests fail with missing x-amz-expiration header. 

test | result
-- | --
test_lifecycle_expiration_header_and_tags_head | success
test_lifecycle_expiration_header_head | fail
test_lifecycle_expiration_header_put | success
test_lifecycle_expiration_header_tags_head | fail

See: s3_expiration_header function in LC. Logs report that the request runs that function to find the correct header, but the function doesn't return one

### PR DESCRIPTION
**Pull request by 0xavi0**
Avoid to return the version id when getting the object from the database
 when it wasn't explicitly required.

A few tags s3tests were failing because, for example:
```c++
int RGWDeleteObjTags::verify_permission(optional_yield y)
{
  if (!rgw::sal::Object::empty(s->object.get())) {
    auto iam_action = s->object->get_instance().empty() ?
      rgw::IAM::s3DeleteObjectTagging:
      rgw::IAM::s3DeleteObjectVersionTagging;
```
If `object->get_instance()` is not empty it changes the action to be looked for to `DeleteObjectVersionTagging`.

The s3test is running in an unversioned bucket and setting the `DeleteObjectTagging` action to be allowed, but it was later looking for a different one.

PR also enables a few `s3tests` related to tagging.

Fixes: https://github.com/aquarist-labs/s3gw/issues/675
Fixes: https://github.com/aquarist-labs/s3gw/issues/695
Signed-off-by: Xavi Garcia <xavi.garcia@suse.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

### CODE REVIEW

**Comment by jecluis** [comment]
@0xavi0 please remove the following tests from the excuses list in `qa/rgw/store/sfs/tests/fixtures/s3tr_excuses.csv`:

```
   Test Name                                     Test Result   Container Exit  
 ──────────────────────────────────────────────────────────────────────────── 
  test_bucket_policy_put_obj_copy_source        fail          success         
  test_bucket_policy_put_obj_copy_source_meta   fail          success         
  test_bucket_policy_put_obj_request_obj_tag    fail          success  
```

**Comment by jecluis** [comment]
> @0xavi0 please remove the following tests from the excuses list in `qa/rgw/store/sfs/tests/fixtures/s3tr_excuses.csv`:
> 
> ```
>    Test Name                                     Test Result   Container Exit  
>  ──────────────────────────────────────────────────────────────────────────── 
>   test_bucket_policy_put_obj_copy_source        fail          success         
>   test_bucket_policy_put_obj_copy_source_meta   fail          success         
>   test_bucket_policy_put_obj_request_obj_tag    fail          success  
> ```

turns out you were faster doing this than I was hitting the "Comment" button :rofl:

File: src/rgw/driver/sfs/types.cc [hunk 1]
```diff
@@ -149,6 +149,12 @@ Object* Object::try_fetch_from_database(
     return nullptr;
   }
 
+  // don't return the version_id if versioning is not enabled
+  // and the user didn't ask for a specific version.
+  // Returning the version_id when no required breaks s3tests related to tags
```
Comment (jecluis) [inline src/rgw/driver/sfs/types.cc:154]: I think it would be more important if we stated that it breaks s3 semantics, rather than the s3tests themselves.

Also, s/when no/when not/

**Review by jecluis — APPROVED** [review]
lgtm minus nit
