### PR TITLE
rgw/sfs: fix build-radosgw.sh not compiling sfs unittests

### LINKED ISSUE #449: rgw/sfs: ceph/qa/rgw/store/sfs/build-radosgw.sh is not building all unittests
ceph/qa/rgw/store/sfs/build-radosgw.sh is not building all unittests.
Specifically: 

```
      UNIT_TESTS <<< "$(awk '/build unittest_rgw_(sfs|s3gw)/ {
                               print $4
                             }' build.ninja)"
```
is not capturing all test files.
Reworking this as:

```
      UNIT_TESTS <<< "$(grep -E "build unittest_rgw_sfs_|build unittest_rgw_s3gw_" build.ninja \
                          | awk 'BEGIN {ORS=" "}; {print $4}')"
```

### PR DESCRIPTION
**Pull request by giubacc**
The UNIT_TESTS variable in the script was initialized with a value that was not capturing all the sfs related unittests.

Fixes: https://github.com/aquarist-labs/s3gw/issues/449
Signed-off-by: Giuseppe Baccini <giuseppe.baccini@suse.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

### CODE REVIEW

File: qa/rgw/store/sfs/build-radosgw.sh [hunk 1]
```diff
@@ -114,11 +114,11 @@ _build() {
...
     # adding a new unit test
-    # SFS unittests should be named unittest_rgw_sfs*
+    # SFS unittests should be named unittest_rgw_sfs_*
+    # SFS unittests should be named unittest_rgw_s3gw_*
     IFS=" " read -r -a \
-      UNIT_TESTS <<< "$(awk '/build unittest_rgw_(sfs|s3gw)/ {
-                               print $4
-                             }' build.ninja)"
+      UNIT_TESTS <<< "$(grep -E "build unittest_rgw_sfs_|build unittest_rgw_s3gw_" build.ninja \
+                          | awk 'BEGIN {ORS=" "}; {print $4}')"
```
Comment (jecluis) [inline qa/rgw/store/sfs/build-radosgw.sh:121]: Ok, after running both commands I finally understand what you are trying to fix. However, the new command does not pick up on an additional unit test that would be picked up by the original `awk` command: `src/test/rgw/sfs/unittest_rgw_sfs`, because the new command expects an underscore after `_rgw_sfs`.

**Review by jecluis — CHANGES_REQUESTED** [review]
should probably pick up on all available unit tests.

File: qa/rgw/store/sfs/build-radosgw.sh (hunk 1 above)
Comment (giubacc) [reply qa/rgw/store/sfs/build-radosgw.sh:121]: the problem with the original command is that:
1. it is capturing also `unittest_rgw_sfs` and `unittest_rgw_s3gw` directories, we want to capture binaries only (with the trailing underscore we should prevent this).
2. it is separating the captured tokens with a newline, but CI is not working as intended due to that; the new patch splits tokens with a space.

**Comment by 0xavi0** [comment]
Also...we have the `unittest_rgw_sfs` target that was created to include all the unittests...
however... looks like newer unit tests have not been added.

I would suggest to use that new target.

**Comment by 0xavi0** [comment]
Also... I liked how tests where discovered by its name, because it helped to ensure that all tests were compiled and it was pretty simple.
That got broken when the new `s3gw_telemetry` unit test was added. 

I suggest to use the same name convention for all unit tests... either we call them `sfs_` or `s3gw_` so things are simple again.

IMHO tests should be named `sfs` because (unless we change it)... our driver is ceph's code is called `sfs`.

If we stick to a single name convention things are simpler and unit tests should not be broken.

That new name broke: 
* unit tests building
* unit tests execution (because the new s3gw test is not executed by the run tests container)
* release.yaml (when trying to discover tests) 

and made everything more complex.

**Comment by giubacc** [comment]
> Also... I liked how tests where discovered by its name, because it helped to ensure that all tests were compiled and it was pretty simple. That got broken when the new `s3gw_telemetry` unit test was added.
> 
> I suggest to use the same name convention for all unit tests... either we call them `sfs_` or `s3gw_` so things are simple again.
> 
> IMHO tests should be named `sfs` because (unless we change it)... our driver is ceph's code is called `sfs`.
> 
> If we stick to a single name convention things are simpler and unit tests should not be broken.
> 
> That new name broke:
> 
> * unit tests building
> * unit tests execution (because the new s3gw test is not executed by the run tests container)
> * release.yaml (when trying to discover tests)
> 
> and made everything more complex.

totally agree on make things simpler! :+1: :+1: :+1:
btw, now we have to make this release and we cannot change things in this cycle.

**Review by m-ildefons — APPROVED** [review]
LGTM

We'll redo the unit test discovery in the future properly. That is tracked [here](https://github.com/aquarist-labs/s3gw/issues/465)

**Review by jecluis — APPROVED** [review]
