### PR TITLE
rgw/sfs: fix delete bucket when not empty

### LINKED ISSUE #325: rgw/sfs: Deleting a bucket with objects does not throw `BucketNotEmpty` error
When deleting a bucket which contains several objects, it is expected that a `BucketNotEmpty` is thrown when trying to delete the bucket via AdminOps API. The bucket should be deleted only if the argument `purge-objects` is set. Check out the API docs [here](https://docs.ceph.com/en/latest/radosgw/adminops/#remove-bucket).

The UI has added this feature by https://github.com/aquarist-labs/s3gw-ui/pull/134. With a connected Ceph RGW this works as expected.

### LINKED ISSUE #577: [BUG] Get unversioned bucket objects with versionId == null
**Describe the bug** A clear and concise description of what the bug is.

After changes introduced in https://github.com/aquarist-labs/ceph/pull/153 we are not able to GET an object inside an unversioned bucket passing `versionId=null`. 

According to the docs. Unversioned buckets add `versionId=null` to all objects, so that GET should be possible.

Only `null` would be valid for unversioned buckets, the rest should return `400`.

This also affects `delete-object` and any other operation.

For example, when deleting all the objects in a bucket `s3tests` list all the object by listing versions.
For unversioned buckets it returns `versionId=null` and we should be able to delete that object.

### PR DESCRIPTION
**Pull request by 0xavi0**
Fixes deleting a bucket when it's not empty.
And also fixes being able to delete and get null versionId for unversioned buckets.
The later is needed for running `s3tests` after fixing the deleting bucket non empty bug, because buckets are deleted in the tearDown call. 
It lists the versions and for unversioned buckets it deletes objects passing `versionID=null`, so we need to support that.

Basically when a bucket is not versioned and `versionId` passed is `null` it is ignored (as if it was not specified)

Fixes: https://github.com/aquarist-labs/s3gw/issues/325
Fixes: https://github.com/aquarist-labs/s3gw/issues/577

Signed-off-by: Xavi Garcia <xavi.garcia@suse.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

### CODE REVIEW

**Comment by 0xavi0** [comment]
Looks like this is going to be more complex than I thought.
There are some tests that fail because they test cases in which the version ends up getting OPEN after a failure and code considers that bucket as NOT empty.

Problem with considering a bucket with OPEN versions empty is that we could have a race condition which could end up potentially in a `SQLite` foreign key error.

Thread 1 starts a put (version is open)
Thread 2 deletes the bucket
**Garbage collectors deletes permanently the bucket and its contents**
Thread 1 finishes the upload and now wants to change the state of the version from OPEN to COMMITTED, but the whole bucket is gone already, including the object.

Moving this to draft and I'm going to investigate a bit more those cases

**Comment by 0xavi0** [comment]
Code is now considering a bucket empty only if has no COMMITTED versions that are no delete markers.

All s3tests pass now.

We still have a possible race condition with the Garbage Collector (if the database bucket was permanently deleted while an upload is taking place)
We could discuss and implement that in a separate PR.

File: src/rgw/driver/sfs/sqlite/sqlite_buckets.cc [hunk 1]
```diff
@@ -97,4 +97,21 @@ std::vector<std::string> SQLiteBuckets::get_deleted_buckets_ids() const {
...
+      inner_join<DBObject>(
+          on(is_equal(&DBObject::uuid, &DBVersionedObject::object_id))
+      ),
+      where(
+          is_equal(&DBVersionedObject::object_state, ObjectState::COMMITTED) and
+          is_equal(&DBObject::bucket_id, bucket_id) and
+          is_equal(&DBVersionedObject::version_type, VersionType::REGULAR)
+      )
+  );
+  return ids.size() == 0;
```
Comment (irq0) [inline src/rgw/driver/sfs/sqlite/sqlite_buckets.cc]: This transfers all ids from SQLite to a std::vector just take the count. Suggest to take the count in SQLite or return a booleanesque value to return a constant size result.

Example:
sqlite> select count(id) > 0 from versioned_objects inner join objects on (uuid = object_id) where object_state == 1 and version_type == 0;

Comment (0xavi0) [reply src/rgw/driver/sfs/sqlite/sqlite_buckets.cc]: I changed to a plain `count` with `inner join` instead of a `select count...` 
That way it returns just the number I'm looking for instead of a vector of ints.

**Review by irq0 — APPROVED** [review]
