### PR TITLE
rgw/sfs: init bucket mtime and store it

### LINKED ISSUE #174: rgw/sfs: The `mtime` field of buckets is not populated
I'm not sure if this is a regression, but with the latest `s3gw` container the [mtime field](https://github.com/aquarist-labs/s3gw-ui/blob/main/src/app/shared/services/api/admin-ops-bucket.service.ts#L26) of the buckets response object (via Admin Ops API) is not populated any more. It only contains `0.00000`.

The API call is: `http://localhost:4300/admin/bucket?stats=true`

Bildschirmfoto vom 2023-03-09 16-00-30

Bildschirmfoto vom 2023-03-09 16-00-22

### PR DESCRIPTION
**Pull request by jecluis**
Fixes: aquarist-labs/s3gw#174

Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

### CODE REVIEW

File: src/test/rgw/sfs/test_rgw_sfs_sfs_bucket.cc [hunk 1]
```diff
@@ -223,6 +227,9 @@ TEST_F(TestSFSBucket, UserCreateBucketCheckGotFromCreate) {
   }
 
   EXPECT_EQ(bucket_from_create->get_acl(), arg_aclp);
+  EXPECT_TRUE(
+      bucket_from_create->get_modification_time().time_since_epoch().count() > 0
```
Comment (irq0) [inline src/test/rgw/sfs/test_rgw_sfs_sfs_bucket.cc]: I think `real_clock::is_zero(ts)` is the canonical way to check that the timestamp is not zero.
Suggest replacing with `EXPECT_NE(real_clock::is_zero(bucket_from_create->get_modification_time()))`

**Comment by jecluis** [comment]
@irq0 please take another look. I'd love to put this one behind us :)

**Review by irq0 — APPROVED** [review]
