### PR TITLE
Fix default retention mode with multipart uploaded objects

### LINKED ISSUE #761: [BUG] rgw/sfs: default retention mode not applied to objects on multipart_upload_v2::complete
[UPDATE] this is a backend issue.

`SFSMultipartUploadV2::complete()` does not perform the same updates on `attrs` made by `SFSAtomicWriter::complete`.
Specifically: the attribute `RGW_ATTR_OBJECT_RETENTION`  is not updated with the bucket's default retention mode. 

**Describe the bug** A clear and concise description of what the bug is.

After having created a bucket with a default retention mode:

image
 
Objects put in the bucket don't have the expected retention mode set:

image

### PR DESCRIPTION
**Pull request by giubacc**
When an object is uploaded with multipart, for object-lock enabled buckets,
the default rentention mode must be set in the object's attributes
(when a retention mode is not explicitely set by the user for the object).
Therefore, `RGW_ATTR_OBJECT_RETENTION` must be set in the attrs of each part
being uploaded in the `SFSMultipartUploadV2::complete()` function.
    
Fixes: https://github.com/aquarist-labs/s3gw/issues/761

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

### CODE REVIEW

File: src/rgw/driver/sfs/multipart.cc [hunk 1]
```diff
@@ -470,6 +470,22 @@ int SFSMultipartUploadV2::complete(
...
+  // profile when not defined on the MP part
+  if (bucketref->get_info().obj_lock_enabled() &&
+      bucketref->get_info().obj_lock.has_rule()) {
+    auto iter = mp->attrs.find(RGW_ATTR_OBJECT_RETENTION);
+    if (iter == mp->attrs.end()) {
+      real_time lock_until_date =
+          bucketref->get_info().obj_lock.get_lock_until_date(
+              ceph::real_clock::now()
+          );
+      string mode = bucketref->get_info().obj_lock.get_mode();
```
Comment (irq0) [inline src/rgw/driver/sfs/multipart.cc]: std::string please

File: src/rgw/driver/sfs/multipart.cc [hunk 2]
```diff
@@ -470,6 +470,22 @@ int SFSMultipartUploadV2::complete(
     return -ERR_INTERNAL_ERROR;
   }
 
+  // for object-locking enabled buckets, set the bucket's object-locking
+  // profile when not defined on the MP part
+  if (bucketref->get_info().obj_lock_enabled() &&
+      bucketref->get_info().obj_lock.has_rule()) {
+    auto iter = mp->attrs.find(RGW_ATTR_OBJECT_RETENTION);
+    if (iter == mp->attrs.end()) {
+      real_time lock_until_date =
```
Comment (irq0) [inline src/rgw/driver/sfs/multipart.cc]: ceph::real_time please

**Review by irq0 — DISMISSED** [review]
Please namespace the types as we do in the rest of the code. Otherwise looks good

**Review by jecluis — APPROVED** [review]
